### ISSUE TITLE
Find a way to compress scenarios to avoid the initial redmew effect of 6MB downloads

### ISSUE THREAD

**Issue by TWLTriston** [Refactorio/RedMew#108]

**Comment by mheguy** [comment]
This would be nice. In its simplest implementation, something that opens a save .zip file and removes the images would be a nice start.
And preferably able to run on windows and linux.

**Comment by Valansch** [comment]
Implemented in admin interface. Deflate button. Written in dotnet, so it runs on windows and linux.

**Comment by mheguy** [comment]
Oh this was around already, I recognize the message. -- You need to update the link :p

**Comment by Valansch** [comment]
What link?

**Comment by mheguy** [comment]
error('File was removed to decrease save file size. Please visit https://github.com/Valansch/RedMew if you wish to download this scenario.')

**Comment by Valansch** [comment]
Ahh that link. Not that it matters, but it's hardcoded in the webinterface :D
