### ISSUE TITLE
Kill count

### ISSUE THREAD

**Issue by Valansch** [Refactorio/RedMew#12]
- Biter kills player: Biter gets a kill, player gets a death.
- Player 1 kills player 2: Player 1 gets a kill player 2 gets a death.
- Player kills biter: Nothing happens.
- Anything else kills player: Player gets death. (Maybe trains get kills too)
- Player kills anything else: Nothing happens.

**Comment by iltar** [comment]
As this is a pretty old issue, is this still something you wish to add or can this feature request be closed?

**Comment by Valansch** [comment]
I still think its cool. It can be added to the player list.

**Comment by plague006** [comment]
I'm not sure what this is about. We track deaths in the player list. We track biter deaths in rocket launch thing.

>Biter kills player: Biter gets a kill
>(Maybe trains get kills too)

Are you saying we should have a full scoreboard and entities with kills should be listed there alongside players?

**Comment by Valansch** [comment]
No just a simple K/D ratio next to the player. But kills only accounts for player kills :D

**Comment by Valansch** [comment]
Meh^^
If two people want to kill each other let them.

**Comment by mheguy** [comment]
This issue is a year old. If someone wanted to implement it they would have. If someone wants to implement it in the future: all power to them. 

However I’m going to close this issue as essentially: will not implement.
