### ISSUE TITLE
suicide forest

### ISSUE THREAD

**Issue by Valansch** [Refactorio/RedMew#14]

**Comment by Valansch** [comment]
/c local pos = game.player.position for k,v in pairs(game.surfaces[1].find_entities_filtered{area = {{pos.x-10, pos.y-10}, {pos.x+10, pos.y+10}}, type= "tree"}) do local current_pos = v.position v.destroy() game.player.surface.create_entity{name="player", position = current_pos, force = game.forces.enemy} end

**Comment by Toledin** [comment]
like logan paul?

**Comment by Valansch** [comment]
Yes.

**Comment by iltar** [comment]
Is this still something that we'd like to have?

**Comment by Valansch** [comment]
Yes :)

**Comment by mheguy** [comment]
Moved to Val's project.
