### ISSUE TITLE
Change thread implmentation

### ISSUE THREAD

**Issue by grilledham** [Refactorio/RedMew#157]
- [x] Change the action queue to a O(1) queue implementation.
- [x]  Add weights to the actions.
- [x]  Remove the concepts in the around threading.
- [ ]  Updates old threads.

I opened this issue so we can have a proper discussion on what we want to do with threads/ actions / tasks / whatever we are calling them.

The hash queue implementation is fairly straight forward, so I'm willing to sort that out / test for desyncs.

Coming from a mainly c# background, I'd rename the whole threading concept to tasks.
- Thread.lua -> Task.lua
- action_queue -> task_queue
- actions / callbacks -> tasks
- Thread.set_timeout_in_ticks -> Task.set_timeout_in_ticks

I am of course open to other naming suggestions.

Regarding action weights, I see there as being 2 approaches:
1. We normalise all actions so that they take roughly the same amount of time per call, thus eliminating the need for weights.
2. We add a cost field to each action's args object that represents the approximate time cost to call that action on an arbitrary scale say 1 - 100. We then have the action queue set to keep running actions until it reaches a cost of say 100. 
I would make this a fixed value and not dynamic as I see the point of the action_queue to reduce execution cost per tick. Having more actions in the queue doesn't mean we should sacrifice performance just that we have to wait longer. And with a better queue implementation, big queue will have a minimal performance impact.
I would also allow the action when run to change it's cost value, because each call to the action might have a different expected time cost.

Let me know what you think. I am also interested in any alternative suggestions you might have.

**Comment by grilledham** [comment]
> Change the action queue to a O(1) queue implementation.

I've had some success with #158 on the test server. 
The test was the island_resort map and chart 2048 tiles around spawn. I did this 4 times and desynced 1 out of 4 times.
Clearly more testing is needed.

**Comment by Valansch** [comment]
It's kinda funny and sad that we consider desyncing 25% of the time as a success :D

**Comment by Valansch** [comment]
So if #158 works we can surely use your queue implementation.

Still open is the question about tasks per second/weight/cost.

**Comment by grilledham** [comment]
I think i still need more time to think about weight/costs.

But I guess a good way to see if it's a good idea is to implement it and see what happens.

**Comment by grilledham** [comment]
I implemented weights. Let me know what you think.

The more I think about it, implementing costs make less sense. If we suspect a task is going to take a long time we should just split it up into smaller tasks.

I was looking a the code for async callbacks and noticed it could probably use some attention.
- It stores the function in the global table, rather than the string for the function name, and I think we decided this can cause problems if we use closures.
- The table that stores the callbacks is unordered, so each tick it has to loop through the whole table.

**Comment by Valansch** [comment]
I think we  can close this now? I think you did a great job. I really like the result.

**Comment by grilledham** [comment]
There is still the issue of updating the old tasks to be reusable tasks where possible.
The following files still use the old style of tasks:
 - borg_planet_v2
 - dagobah_swamp
 - red_planet_v2
 - mines
 - worms

**Comment by Valansch** [comment]
Okay noted. So i will keep this issue open.

**Comment by mheguy** [comment]
Is all of this out of date/implemented to your satisfaction?

**Comment by grilledham** [comment]
Yeah I think we finished this.
