### ISSUE TITLE
Fix tabs in entire project

### ISSUE THREAD

**Issue by Valansch** [Refactorio/RedMew#206]
I think we should finally agree on a standard.
@grilledham uses 4 spaces. I have been using a bit of everything so i guess most of the inconsistency a due to me.

So can we agree to 4 spaces?

**Comment by grilledham** [comment]
I use 4 spaces because it's what my text editor defaults to. But my preference is for 4 spaces as I find that easier to read.

**Comment by grilledham** [comment]
I have an autoformatter that will fix indentation, but it will also apply other formatting rules, such as trying to keep lines less than 140 characters, turning `"` into `'`, etc

**Comment by Valansch** [comment]
Those rules are fine by me too

**Comment by iltar** [comment]
You mean `'` over `"`? I really don't care either. `"` is consistent with the string definition in pretty much all languages, but takes shift to type. `'` is consistent across scripting languages that don't have the notion of a char.
