### ISSUE TITLE
Add a toggle for logistics requests

### ISSUE THREAD

**Issue by plague006** [Refactorio/RedMew#217]
Something based on https://github.com/peet1993/SupplyToggle/blob/master/control.lua but with a GUI hook since scenario code can't extend keybinds?

In addition maybe have it automatically toggle off on death?

**Comment by theorangeangle** [comment]
Irrelevant in 0.17 - will be in base game as announced in FFF 280 https://cdn.factorio.com/assets/img/blog/fff-280-shortcut-bar.png

**Comment by theorangeangle** [comment]
i was fed false information! ignore this

**Comment by mheguy** [comment]
Moved to my project.
