### ISSUE TITLE
Add donator rank perks

### ISSUE THREAD

**Issue by theorangeangle** [Refactorio/RedMew#218]
Currently we have 3 perks offered to our patreons that need to be implemented ingame. Some of these perks are offered at different tiers, so noting the tier level [as shown here](https://www.patreon.com/redmew) is something that needs to be added to donators.lua

- Personalized welcome message for all to see when joining the game - $3 tier
_Easy enough, just need to ask the patrons what they want their message to be._

- Free train invincibility and extra ingame currency for market - $5 tier
_Train invincibility should be working, just need to give it to free for those with the $5 and up tier; as for the extra ingame currency I think we decided on 50 coins instead of 10? Not sure_

- Something TBD to make the in-game experience better for you and your name on the reddit sidebar and website - $10 tier
_For the $10 tier we still need to find a perk that makes the donators appeased without breaking game balance - IMO hand crafting speed might be viable but we can table it for now; reddit sidebar I can take care of and website is @Valansch's end_

The donator rank itself is already working, so that takes care of the $1 tier.

**Comment by Valansch** [comment]
So what do you want me to do on the website? Show a donator list? Or is that TBD?

**Comment by theorangeangle** [comment]
For the website we could put a banner below the buttons with the names, or maybe a banner at the top of the saves download menu with something along the lines of "Thanks to all our patreons who help support redmew - especially _________. If you enjoy these maps then please consider supporting us at patreon.com/redmew.

**Comment by Valansch** [comment]
I dont think we need the link since its already on there. But we can put the thank you message somewhere. Do you have a mockup that i could follow?

**Comment by theorangeangle** [comment]
Not really - I guess what I pasted above works fine

"Thank you to all our patreons who support us! - especially <insert names here>"

Or maybe we have something that pops up after you download a map saying, "Thank you for downloading this map! If you like what you see here, consider supporting us on patreon and join <number of patreons> others in supporting the best mapgen in factorio."

**Comment by theorangeangle** [comment]
So mew and I were talking - we should probably stay away from anything resembling P2W as a donator perk, Therefore,I move that we scrap the train invincibility and extra coins for the time being. The personalized message (i'll ask around over the next couple days) and

**Comment by M3wM3w** [comment]
Please, just come up with any creative ideas, just don´t alter game mechanics.
No items.
No boosts.
Nothing that alters gameplay.
We need something that fits every kind of map and style of scenario!
Honor our patreons differently!

**Comment by Valansch** [comment]
We discusses this in the admin channel, you did not reply to it when it was discussed multiple times. We already promised those features. I feel when we promise something to someone who gives us $30/month we better deliver it. Not saying we cannot change it but the players who donated under these conditions should get their rewards at least.

**Comment by grilledham** [comment]
I favour not having any so called pay to win perks. I think initially when we set this up we wanted to have appealing perks to attract donations. But I think people have donated because they like the work we have already done and want to support that. 

So with the benefit of hindsight I don't think we need the perks that offer individual advantages.

**Comment by der-dave** [comment]
My idea some days before was to play a small (max. 5 secs) sound when a donator enters the server. but this didnt work without the use of mods. As an extra the sound could be uploaded via website.
Maybe there is a chance to play a sound with the speaker already implemented in game?

**Comment by mheguy** [comment]
Everything that has been agreed on has been implemented. While we would like more perks for donators, I don't think this issue needs to be open. Anybody who thinks of a perk can open an issue for discussion about it.
