### ISSUE TITLE
Disable /kill for players on a walkabout

### ISSUE THREAD

**Issue by Valansch** [Refactorio/RedMew#22]

**Comment by plague006** [comment]
Can you expand on this? Do you want players on walkabout to be invulnerable to /kill ?

**Comment by Valansch** [comment]
It was never a big issue, but people on a walkabout can use /kill to be teleported back to spawn and grief there. We don't want that.

**Comment by grilledham** [comment]
Walkabout also has issues with the temp bonus from the market, and players leaving before the walkabout finishes. There are a lot of edge cases that need to be handed with care, so it might take some time to complete rewriting / testing.
