### ISSUE TITLE
Market speed buffs assumes each Player always has a Character.

### ISSUE THREAD

**Issue by FoolishOne9k2** [Refactorio/RedMew#224]
We've been encountering this error in our logs recently:

> 62817.338 Script .../utils/event.lua:22: No character.
> stack traceback:
> 	.../fish_market.lua:223: in function 'reset_player_runningspeed'
> 	.../fish_market.lua:377: in function <.../fish_market.lua:372>
> 	[C]: in function 'pcall'
> 	.../utils/event.lua:20: in function 'call_handlers'
> 	.../event.lua:45: in function <.../utils/event.lua:43>

It looks like we had a player buy a speed buff, die before the buff expired, and then leave the game before respawning. They still have an entry in the `global.player_speed_boost_records` table.

When fish_market.lua changes `character_running_speed_modifier` it does so using the `LuaPlayer` object as its reference. According the [Lua documentation](https://lua-api.factorio.com/latest/LuaControl.html#LuaControl.character_running_speed_modifier) this can fail as a `Player` doesn't always have to have a `Character`. 

What it looks like we have is a `Player` in the `global.player_speed_boost_records` table, that doesn't have a `Character` associated. This causes an error when trying to set their `character_running_speed_modifier`, which event.lua's `pcall` protects us from and logs. This runs every 3 seconds and fills our logs.

A copy of the save can be found in our public read FTP. [Here](https://vault.win-serv.com/publicstorage/DYNAMIC-NETWORKS-READ-ONLY/GameServ/Factorio.one/01d/saves/_gsdata_/_history_/_autosave1_2018-0927-114556.zip)

The player in question is player index 12, they have a `ticks_to_respawn` value and no inventory so I believe they are dead. 

A quick fix I tested is to put a check if the player has a character around setting the value each time. IE:
```
if (player.character) then
    player.character_running_speed_modifier = global.player_speed_boost_records[player.index].pre_boost_modifier
    global.player_speed_boost_records[player.index] = nil
end
```
Though this would be cumbersome in the long run.

This applies to quite a few properties that are shared between `Character` and `Player` but really only apply to `Character`.

What should be done about this? I can probably make the changes and submit a pull with a bit of direction.

**Comment by plague006** [comment]
Would it be possible to always target the character and not the player?

**Comment by Valansch** [comment]
Depends on what you want to do. Character represents the entity. Player represents the client controlling it.
Some fields are the same for both but most of the time you either work on the character *or* the player
