### ISSUE TITLE
Admin chat suggestions, change the color to clearly distinguish the type

### ISSUE THREAD

**Issue by iltar** [Refactorio/RedMew#279]
I'm not sure how easy this would be, but my suggestion is to alter the color of the admin chat slightly. Perhaps we can play around with white + a slight shade of the player color? The `(Admin)` is (for me) hard to see as there's also player tags: `(Admin) PlayerName [sometag with some text]` in all different colors.

**Comment by plague006** [comment]
I'll take this on

**Comment by SimonFlapse** [comment]
![image](https://user-images.githubusercontent.com/44922798/48548658-ce301f00-e8cd-11e8-86f3-c26294267f68.png)

I just had a quick look at it. The above is a suggestion of how we could make it stand out some more. Inspired by #337 
You could also just remove the tag and implement the other ideas like those previously proposed. I don't see why a tag is useful in the admin chat.

**Comment by iltar** [comment]
What does this look like with multiple admin chats (from multiple players)?

**Comment by SimonFlapse** [comment]
Since it's just a mock up the 'Admin Chat' line will display every time someone writes. Which I think isn't optimal.
Tried to simulate it:
![image](https://user-images.githubusercontent.com/44922798/48549075-0e43d180-e8cf-11e8-9273-f9ad21fa05d6.png)

**Comment by iltar** [comment]
What if we keep track of whether the previous message was an admin message, and if so, omit it? That way it will toggle itself back on automatically. Perhaps we could do the same for "player chat"? Or am I over-bloating the feature now?

**Comment by SimonFlapse** [comment]
That would be the solution, but I think it's overkill. Made another mockup:
![image](https://user-images.githubusercontent.com/44922798/48549355-d7ba8680-e8cf-11e8-8026-7f8d8e099a40.png)

**Comment by iltar** [comment]
That would (imo) also be clear enough for just admin channels

**Comment by SimonFlapse** [comment]
@plague006 Any other ideas or plans? I can have the code ready in a couple of minutes if you'd like

**Comment by plague006** [comment]
I've been working on admin chat and giving more feedback on commands for a few days, can definitely incorporate the 2 hashtags and the dash.

This is the extant code in what I'm working on for print_admin specifically:

```lua
-- Takes a LuaPlayer or string as source
Module.print_admins = function(msg, source)
    local source_name
    local chat_color
    if source then
        if type(source) == 'string' then
            source_name = source
            chat_colot = game.players[source].chat_color
        else
            source_name = source.name
            chat_color = source.chat_color
        end
    else
        source_name = "Server"
        chat_color = {r=255, g=255, b=255}
    end
    for _, p in pairs(game.connected_players) do
        if p.admin then
            p.print(string.format('(ADMIN) %s: %s', source_name, msg), chat_color)
        end
    end
end
```

**Comment by SimonFlapse** [comment]
@plague006 do you feel this is ready to be closed, given your additions to admin chat?

**Comment by plague006** [comment]
I think things are in a good place. We can always tweak later.
