### ISSUE TITLE
Codify the terminology we use for maps

### ISSUE THREAD

**Issue by plague006** [Refactorio/RedMew#298]
In a perfect world, anyone could open up `map_layout.lua` and actually make sense of what can be combined with what. With that goal in mind I have a few interconnected proposals.

1. Presently in `map_layout.lua` we use some terms but don't define them:
`combined`, `presets`, `shapes`, `terrain`, `entity_modules`, `terrain_modules`, `everything else`
It would be nice to have these, and some other terms and definitions codified so that we can better categorize the files/modules in the repository and create clearer documentation.

2. I would like to have `map_layout.lua` split into 2 files. One which allows a user to create their own map by selecting modules, and one that only has preset maps and scenarios to allow the user to easily load up their favourite map/scenario in the easiest way possible.

So as a jumping off point to creating a map building vocabulary we can all share and agree on I have the following:

`the map`
A collective term for the tiles, entities, and resources which make up the game surface.

`resources`
A subset of entities which include coal, iron, copper, oil, stone, and uranium.

`significant gameplay features`
Gameplay changes beyond the enabling/disabling of recipes/techs and altering the market.

`shape_module`
Creates shapes only by turning tiles to void. Conflicts with `terrain_module`s. May conflict with other `shape_module`s. Does not affect entities or resources. (ex. x_shape)

`terrain_module`
Creates specific designs by changing tiles to other types of tiles. Conflicts with `shape_module`s and other `terrain_module`s. Does not affect entities, resources, or gameplay.  (ex. )

`ore_module`
Creates specific designs or patterns with resources. May replace vanilla ore generation. Does not affect tiles or gameplay. May conflict with other `ore_module`s. Should not, but may, affect entities. Whether a module removes vanilla ore generation or not should be included in a comment at the top of the file. (ex. glitter_ores)

`entity_module`
Creates specific designs or patterns with entity placement. Does not affect resources, tiles, or gameplay. May conflict with other `entity_module`s. May affect vanilla generation of entities. Whether a module removes vanilla entity generation or not should be included in a comment at the top of the file. (ex. worms)

`gameplay_module`
Only adds gameplay elements. May not affect the map. (ex. danger ores)

`day_night_cycle_module` 
Only sets the day/night cycles of a map. May not affect the map or gameplay.

----

`preset_map`
A lua file that is meant to be run with no other modules. May affects the map, resource, and/or entity generation. Does not introduce significant gameplay features/changes.

`scenario`
A lua file (or set of files) that is/are meant to be run with no other modules. Affects the map, resource, and entity generation. Adds significant gameplay features. (ex. diggy, crash site, biter battles)

(It's 2am, I'm sorry if this is a garbled mess)

**Comment by iltar** [comment]
>>I still have to move Diggy to the correct directory, I'll do this asap
>At this point you may as well wait for this issue to come to some kind of consensus. Easier to just move it >one time, when a more long-term directory structure has been figured out

The consensus at the moment is (or was), is that Diggy is supposed to be next to the cave miner. If I move it there, it's at least consistent. You're right that it will cause a second move.

**Comment by mheguy** [comment]
So I've given this a major re-think/been persuaded to think of things differently. I was previously thinking of map_layout as the center and everything feeding into it. Instead I want to think of each map/preset as the center with features, configs, and data feeding into it.

Every file that defines a map is a preset, which is interchangeable with map or scenario. Each preset/map/scenario has 1 file in the `presets` folder. The `presets` folder has no sub-folders.

`features` contain all modules that affect map-specific gameplay (ex. ArtefactHunting). If maps absolutely require features that can't be made accessible to other maps, they can create sub-folders. If multiple modules execute the same feature with variations they should be contained within a sub-folder (ex. ore generators).

Some maps need their own configs, these should sit in `configs`.

Many maps and/or features require files with nothing but data/patterns inside them. These should be stored in data inside subfolders that describe what kind of data it is. (Ex. Map shape data from images, outpost data)

`shared` is essentially `utils` for maps. It contains libraries that perform the actual world generation or other functions relevant to most or many maps.

I have created a sample of what the structure might look like: https://github.com/Refactorio/RedMew/tree/dummy

Or for a quick visual: 
![image](https://user-images.githubusercontent.com/10162554/49568365-d1339380-f8fe-11e8-8ce8-47ce092eee2c.png)

**Comment by linaori** [comment]
Very interesting! This would only work if everything follows the same structure in files though (which I would love to have)

**Comment by Valansch** [comment]
>shared is essentially utils for maps. It contains libraries that perform the actual world generation or other functions relevant to most or many maps.

Shared is NOT utils, as it contains both shared libraries and libraries frameworks. If we moved the framework files into another foulder you could call it utils/lib.

**Comment by mheguy** [comment]
> Shared is NOT utils

You know me, I'm not the best with names. So if you don't like me referring to `shared` as `utils for maps` that's fine: it's just my head canon. `shared` doesn't *need* to change, the key is that we all have the same general understanding of what goes into the folder and what doesn't.

> This would only work if everything follows the same structure in files though

If people get on board with the structure, I'll do the work to move the files where they should be and change the pointers to them.

**Comment by mheguy** [comment]
I feel the meaning of `scenario` and `map` get muddied if `Diggy` `Crashsite` and `RedMew` are all somehow scenarios.

I think I would push for black and white `scenario` = the RedMew codebase and `maps` = maps. Some are complex such as diggy and some are simple like diagonal ribbon but they're all maps.

**Comment by mheguy** [comment]
With the new file structure we have maps, terrain modules, and entity modules. Fairly clear.
