### ISSUE TITLE
Codify the types of (non-mapgen) modules RedMew has in its codebase

### ISSUE THREAD

**Issue by plague006** [Refactorio/RedMew#307]
> Perhaps something else we can expand upon after this (also due to your other PR that nicely splits stuff from the root), is clarify the features, framework utilities and code utilities. RedMew has quite the code-base by now, but it's hard to distinguish the following:
> - Which utilities hook into the core Lua Library
> - Which utilities are enhancing game aspects
> - Which utilities are providing just a set of utilities so we don't have to write them manually
> - Which utilities are debug only
> - Which features exist, what they do and what they should be used for (they lack documentation)
> - Which features are required to run a RedMew server (such as the GUI help icon)
> - Which features can be turned off (or not turned on in the first place)
> - What configuration is required for features when present

>My take on this is the following:
> - `control.lua` should only and always contain all and only _calling_ code required to bootstrap the RedMew framework, and only the bare minimal. This will make it clear to see what functionality makes RedMew, RedMew.
> - Anything in the RedMew framework, should easily be extendible/configurable, meaning it should be easy to hook into the top GUI score board and add a string to the "biters liberated" popup. If this is not the case, it's not part of the RedMew framework, but a feature you can turn on, off or configure otherwise.
> - RedMew framework configuration should go to `config.lua`, and only RedMew configuration should go here.
> - Feature config should be passed along or defined when requiring the features. For example: no global fish market config in `config.lua`, it's up to the scenario to start it (Diggy, Crash Site, Biter Battles, Shapes etc).
> - Features should be made as generic as possible and try to avoid depending on other features. If they _can_ depend on others, use events or callbacks to integrate them, meaning scenarios can easily re-use them. Features should be as isolated as possible and not leak anything outside, to prevent causing unwanted side-effects. Automatically spawning a market should not happen for example, the scenario should initiate this. If it's not useful to make it generic, it's scenario specific and should be included as such.
> - Try to push dependencies upwards. A feature should not depend on another feature. Instead, the "shared" or "dependent" code should be pushed upwards, to a utility (not the correct term though). Example: A lot of diggy features depend on the digging concept, but a Diggy feature should not depend on another, so the can be independently turned off. Instead of depending on "player dug a diggy hole here", the concept was pushed into the `Template.insert` "utility", meaning that features can depend on this generic event fired, rather than a feature specific event. Lua can't handle circular dependencies between features, so this is a nice way of solving that.

>There's probably more that I forgot 🤔

_Originally posted by @iltar in https://github.com/Valansch/RedMew/issues/298#issuecomment-437665628_

**Comment by mheguy** [comment]
I think I'm comfortable with where things are for now. Utils are relatively well defines, as are features and GUI.

@iltar if you're cool with how things are, can we close this?

**Comment by linaori** [comment]
Sure! It's already a great improvement and I think we can create an issue/pr for the remaining things if we encounter issues
