### ISSUE TITLE
Biter Battle Issues

### ISSUE THREAD

**Issue by theorangeangle** [Refactorio/RedMew#349]
Some attention has been drawn to biter battles lately, and people have noted that some things are broken ingame, notably:

-Spy feature eats fish but does not give access 
-Map restart inconsistent (spiral ore and/or rocket silo is sometimes not generated)

I will make a separate issue for some high priority improvements. We should also get a “biter battle” tag for the github repository but I don’t know how to create a tag.

**Comment by plague006** [comment]
Creating and assigning tags is for collabs and owner

**Comment by mheguy** [comment]
Closing as BB is being resumed by mew
