### ISSUE TITLE
Highlight menu items that are active

### ISSUE THREAD

**Issue by linaori** [Refactorio/RedMew#364]
I honestly have no idea how this is supposed to work, but it would be a really awesome feature. Just now I was fanatically clicking all of them to find the one I closed

**Comment by plague006** [comment]
By menu items you mean GUI windows?

**Comment by iltar** [comment]
Correct, a visual indication on the player button, if the player window is active

**Comment by Rdjrjqouqcu** [comment]
I think this might be possible if you changed the background color of the button when the GUI was activated, then change it back when the GUI is deactivated
