### ISSUE TITLE
Allow our GUI buttons to collapse

### ISSUE THREAD

**Issue by plague006** [Refactorio/RedMew#383]
Our friends at explosive gaming have a feature I really want: a button that collapses all their GUI buttons. I think it's an amazing idea and would love if we had it as well.

Their code is under the GPL license so we can just take inspiration or if we want to attribute it back to them we can take as much as we need: https://github.com/explosivegaming/scenario/blob/release/4.0.0/modules/ExpGamingCore/Gui/src/toolbar.lua

![image](https://user-images.githubusercontent.com/10162554/48666729-81974000-ea95-11e8-9453-74ab0ca053b1.png)

**Comment by SimonFlapse** [comment]
It's a nice little QoL feature

**Comment by iltar** [comment]
I would also love to have a clear separation of menu items. Currently when registering for a scenario (say Diggy), they are placed on the left, while ideally I'd have them on the right, perhaps with a label saying "Diggy". I'm hoping to make the buttons a bit more visible like that.

**Comment by plague006** [comment]
Most likely this would require a refactoring of existing GUI elements. It's likely best left for post-0.17.
