### ISSUE TITLE
Clarify the structure of the downloaded scenario

### ISSUE THREAD

**Issue by linaori** [Refactorio/RedMew#405]
In both diggy and the redmew scenario documentation we should clarify what the final structure should look like, to avoid people from extracting the diggy or redmew directory in a second directory, resulting in `control.lua` being 1 level too deep.

**Comment by curiosity-a** [comment]
Copying some of my thought over from Discord:

- The archive does contain a folder already. You would be better off saying to extract to mods and rename Redmew-develop to Diggy.
- Personally, I would expect people to interpret "make sure there is control.lua" as "move control.lua from Redmew-develop to Diggy".

**Comment by plague006** [comment]
I'm pushing to get a release out. With it we can simply call the folder inside diggy.zip `diggy` and make the instructions shorter and easier.

**Comment by SimonFlapse** [comment]
I'd really love official releases, or at least tags! We need a stable version to distribute instead of having people download the latest version that most certainly have some kind of bug

**Comment by plague006** [comment]
My goal is to have one by end of day (GMT-5 time)

**Comment by SimonFlapse** [comment]
For everything or diggy specifically?

**Comment by plague006** [comment]
Everything for this release

**Comment by mheguy** [comment]
With automated releases and an adequate wiki, I believe this issue is resolved.
