### ISSUE TITLE
Create an administrative menu

### ISSUE THREAD

**Issue by TWLTriston** [Refactorio/RedMew#64]
Toggle Button: Force Toggle
Others??

**Comment by TWLTriston** [comment]
Add admin buttons to the player list --- TP to player, Invoke player, Jail

**Comment by Valansch** [comment]
- [ ]  Tpplayer button on player list
- [ ] Force Toggle Button
- [ ] TP mode toggle Button
I think we dont need the other features like detrain and stuff. Since we dont use them too much and usually just dick around with them.

**Comment by theorangeangle** [comment]
Is this still being considered? With the report feature added, it may be time to bring other admin controls under one roof in terms of GUI.

**Comment by Valansch** [comment]
It could be part of the new "?" Menu

**Comment by theorangeangle** [comment]
Maybe clicking on the players name in the reports menu would bring up the options? This is the prime opportunity when less common commands would be used. 
![factorio_2018-09-03_12-19-06](https://user-images.githubusercontent.com/36866626/45007204-55097700-afc2-11e8-98b9-c2a0452d37b5.png)

(that's the only screenshot of the report menu I have on hand)

**Comment by iltar** [comment]
Is this still something we'd like to work on?

**Comment by Valansch** [comment]
Personally not. But maybe others want it? What features would this admin menu really hold? /forcetoggle was removed.

**Comment by SimonFlapse** [comment]
#292 added the jail button in the reports menu. We could add other buttons there. Not sure what other buttons would be useful since they just provide a shortcut for a command

**Comment by SimonFlapse** [comment]
I think that's a good idea. Just change the code for the report button for admins to instant toggle jail. The same for the button in the show report gui.
