### ISSUE TITLE
Enemy Technology for Turrets -- Borg

### ISSUE THREAD

**Issue by TWLTriston** [Refactorio/RedMew#88]
Have enemy technology for turret upgrades mirror player team to ensure a progressive difficulty.

**Comment by theorangeangle** [comment]
Probably should be lumped with recursive biters in terms of enable/disable if implemented

**Comment by plague006** [comment]
I’m going to close this since borg is an abandoned map and nobody seems interested in implementing this or even running the map itself.

**Comment by mheguy** [comment]
I’m going to close this since borg is an abandoned map and nobody seems interested in implementing this or even running the map itself.

**Comment by mheguy** [comment]
Moved to Val's project.
